### PR TITLE
Added version checking to release script. Fixes #288. Also fix bugs with examples in orb

### LINKED ISSUE #288: Release Orb Script should check version
apparently older versions of the circleci CLI don't work with this script.  Need to add a check to handle that.

### PR DESCRIPTION
**Pull request by sudermanjr**

### CODE REVIEW

File: release-orb.sh [hunk 1]
```diff
@@ -1,11 +1,22 @@
...
+    test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
+}
 
+echo "Starting release."
 
 command -v circleci >/dev/null 2>&1 || { echo >&2 "I require circleci but it's not installed.  Aborting."; exit 1; }
 echo "Found circleci command."
 
+cli_version=$(circleci version | cut -d+ -f1)
+required_version=0.1.5705
```
Comment (ejether) [inline release-orb.sh]: Do you want this to be a static version?
`circleci update check` could do some of the work

Comment (sudermanjr) [reply release-orb.sh]: I think so, yeah.  If we change the functionality of the script, we can change the minimum version.  That update check doesn't work for everyone:

```
└─ circleci update check
`update` is not available because this tool was installed using `homebrew`.
Please consult the package manager's documentation on how to update the CLI.
```

Comment (ejether) [reply release-orb.sh]: Boo.. Carry on.
